home/urls.py
from django.urls import path
from . import views


app_name = 'Home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='Home'),
]

khadije/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('model/', include('model.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

model/urls.py
from django.urls import path
from . import views




app_name = 'Model'
urlpatterns = [
    path('details/<int:pk>', views.ModelDetailsView.as_view(), name='ModelDetailsView'),
    path('dutch/', views.DutchModelListView.as_view(), name='DutchModelListView'),
    path('french/', views.FrenchModelListView.as_view(), name='FrenchModelListView'),
    path('mexican/', views.MexicanModelListView.as_view(), name='MexicanModelListView'),
    path('fishtail/', views.FishTailModelListView.as_view(), name='FishTailModelListView'),
    path('chignon/', views.ChignonModelListView.as_view(), name='ChignonModelListView'),
    path('journal/', views.JournalModelListView.as_view(), name='JournalModelListView'),
    path('spiral/', views.SpiralModelListView.as_view(), name='SpiralModelListView'),
    path('about/', views.AboutView.as_view(), name='AboutView'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView
from model.models import Model





class HomePageView(TemplateView):
    template_name = 'home/home.html'
    model = Model

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['french'] = Model.objects.filter(name_en='french')
        context['dutch'] = Model.objects.filter(name_en='dutch')
        context['mexican'] = Model.objects.filter(name_en='mexican')
        context['fishtail'] = Model.objects.filter(name_en='fishtail')
        context['chignon'] = Model.objects.filter(name_en='chignon')
        return context

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} خدیجه بیعتی نژاد | بافت | حنا {% endblock %}
{% block content %}
    <header>
        <div class="Site_description">
            <p class="S_title">به دنیای زیبایی و هنر بافت مو خوش آمدید</p>
            <p class="S_text">در اینجا، ما به شما کمک می‌کنیم تا بافت‌های زیبا و منحصر به فردی را تجربه کنید که نه تنها
                ظاهر شما را زیباتر می‌کند، بلکه اعتماد به نفس شما را نیز افزایش می‌دهد. هنر بافت مو، از قدیمی‌ترین و
                زیباترین هنرهای آرایشگری است که با استفاده از تکنیک‌های مختلف، می‌تواند جلوه‌ای خاص و متفاوت به موهای
                شما ببخشد.

                ما در این سایت، با ارائه آموزش‌های تصویری و نکات حرفه‌ای، شما را در مسیر یادگیری و اجرای انواع بافت‌های
                مو همراهی می‌کنیم. از بافت‌های ساده و روزمره تا بافت‌های پیچیده و مجلسی، همه و همه در اینجا برای شما
                فراهم شده است.

                با ما همراه شوید و زیبایی و هنر را به موهای خود هدیه دهید</p>
        </div>
        <div class="work_texture">
            <li class="title">انواع مختلفی از بافت مو وجود دارد که هر کدام زیبایی و جذابیت خاص خود را دارند</li>
            <li><a href="{% url 'Model:FrenchModelListView' %}">بافت فرانسوی</a>: بافتی که از بالای سر شروع می‌شود و به
                تدریج به سمت پایین می‌آید
            </li>
            <li><a href="{% url 'Model:DutchModelListView' %}">بافت هلندی</a>: مشابه بافت فرانسوی است، اما بافت‌ها به
                جای اینکه به داخل بروند، به بیرون
                می‌آیند
            </li>
            <li><a href="{% url 'Model:FishTailModelListView' %}">بافت ماهی</a>: بافتی که شبیه به دم ماهی است و با
                استفاده از دو بخش مو انجام می‌شود
            </li>
            <li><a href="{% url 'Model:MexicanModelListView' %}">بافت آفریقایی</a>: بافت‌های کوچک و محکم که به طور معمول
                در موهای طبیعی آفریقایی انجام می‌شود
            </li>
            <li><a href="{% url 'Model:ChignonModelListView' %}">شینیون بافت</a>: شینیون بافت مو به مجموعه‌ای از تکنیک‌ها و سبک‌های مختلف اطلاق می‌شود که در آن موها به صورت بافت‌های پیچیده و زیبا جمع و تنظیم می‌شوند
            </li>
            <li><a href="{% url 'Model:JournalModelListView' %}">بافت ژورنالی</a>: بافت‌های ژورنالی معمولاً شامل ترکیب‌های پیچیده و هنری هستند که نیاز به مهارت‌های پیشرفته در بافتن مو دارند
            </li>
            <li><a href="{% url 'Model:SpiralModelListView' %}">بافت اسپیرال</a>: در بافت اسپیرال، موها به صورت دایره‌ای و پیچیده به دور هم بافته می‌شوند و نتیجه کار یک الگوی حلزونی و زیبا را به نمایش می‌گذارد
            </li>
        </div>
    </header>
    <section>
        <p class="Box_title"><a href="{% url 'Model:FrenchModelListView' %}">مدل فرانسوی</a></p>
        <div class="Box_Scroll">
            {% for model in french %}
                <div class="Item_image">
                    <a href="{% url 'Model:ModelDetailsView' model.id %}"><img class="image_model"
                                                                               src="{{ model.image.url }}"
                                                                               alt="{{ model.combined }}"></a>
                    <p><a href="{% url 'Model:FrenchModelListView' %}">{{ model.name_fa }}</a></p>
                </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <p class="Box_title"><a href="{% url 'Model:DutchModelListView' %}">مدل هلندی</a></p>
        <div class="Box_Scroll">
            {% for model in dutch %}
                <div class="Item_image">
                    <a href="{% url 'Model:ModelDetailsView' model.id %}"><img class="image_model"
                                                                               src="{{ model.image.url }}"
                                                                               alt="{{ model.combined }}"></a>
                    <p><a href="{% url 'Model:DutchModelListView' %}">{{ model.name_fa }}</a></p>
                </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <p class="Box_title"><a href="{% url 'Model:MexicanModelListView' %}">مدل مکزیکی</a></p>
        <div class="Box_Scroll">
            {% for model in mexican %}
                <div class="Item_image">
                    <a href="{% url 'Model:ModelDetailsView' model.id %}"><img class="image_model"
                                                                               src="{{ model.image.url }}"
                                                                               alt="{{ model.combined }}"></a>
                    <p><a href="{% url 'Model:MexicanModelListView' %}">{{ model.name_fa }}</a></p>
                </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <p class="Box_title"><a href="{% url 'Model:FishTailModelListView' %}">مدل تیغ ماهی</a></p>
        <div class="Box_Scroll">
            {% for model in fishtail %}
                <div class="Item_image">
                    <a href="{% url 'Model:ModelDetailsView' model.id %}"><img class="image_model"
                                                                               src="{{ model.image.url }}"
                                                                               alt="{{ model.combined }}"></a>
                    <p><a href="{% url 'Model:FishTailModelListView' %}">{{ model.name_fa }}</a></p>
                </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <p class="Box_title"><a href="{% url 'Model:ChignonModelListView' %}">مدل تیغ ماهی</a></p>
        <div class="Box_Scroll">
            {% for model in chignon %}
                <div class="Item_image">
                    <a href="{% url 'Model:ModelDetailsView' model.id %}"><img class="image_model"
                                                                               src="{{ model.image.url }}"
                                                                               alt="{{ model.combined }}"></a>
                    <p><a href="{% url 'Model:ChignonModelListView' %}">{{ model.name_fa }}</a></p>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}