account/urls.py
from django.urls import path
from . import views



app_name = 'Account'

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='Login'),
    path('register/', views.RegisterPageView.as_view(), name='Register'),
    path('logout/', views.LogoutPageView.as_view(), name='LogoUt'),
    path('forgot_password/', views.ForgotPasswordPageView.as_view(), name='ForgotPassword'),
    path('confirm_code/<str:token>', views.VerifyEmailPageView.as_view(), name='VerifyEmail'),
    path('new_password/<str:token>', views.NewPasswordPageView.as_view(), name='NewPassword'),
    path('confirm_registration_code/<str:token>', views.ConfirmRegistrationCodeView.as_view(), name='ConfirmRegistrationCode'),
    path('user_panel/<int:id>', views.UserPanelView.as_view(), name='UserPanel'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'Home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='Home'),
]

khadije/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('model/', include('model.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

model/urls.py
from django.urls import path
from . import views




app_name = 'Model'
urlpatterns = [
    path('details/<int:pk>', views.ModelDetailsView.as_view(), name='ModelDetailsView'),
    path('dutch/', views.DutchModelListView.as_view(), name='DutchModelListView'),
    path('french/', views.FrenchModelListView.as_view(), name='FrenchModelListView'),
    path('mexican/', views.MexicanModelListView.as_view(), name='MexicanModelListView'),
    path('fishtail/', views.FishTailModelListView.as_view(), name='FishTailModelListView'),
    path('chignon/', views.ChignonModelListView.as_view(), name='ChignonModelListView'),
    path('journal/', views.JournalModelListView.as_view(), name='JournalModelListView'),
    path('spiral/', views.SpiralModelListView.as_view(), name='SpiralModelListView'),
    path('about/', views.AboutView.as_view(), name='AboutView'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--========== My Links ==========-->
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />

    <!--========== My Files Css ==========-->
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/account.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/details.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/Texture_Model.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}"/>


    <title>{% block title %}  {% endblock %}</title>
</head>
<body>


<div class="notifications_NOT_WQwqzadb">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == 40 %}
                <div class="toast error" data-time="5">
                    <i class="bi bi-shield-fill-exclamation"></i>
                    <div class="content">
                        <div class="title">Error</div>
                        <p>{{ message }}</p>
                    </div>
                </div>
            {% elif message.level == 25 %}
                <div class="toast success" data-time="5">
                    <i class="bi bi-shield-fill-exclamation"></i>
                    <div class="content">
                        <div class="title">Success</div>
                        <p>{{ message }}</p>
                    </div>
                </div>
            {% else %}
                <div class="toast info" data-time="5">
                    <i class="bi bi-shield-fill-exclamation"></i>
                    <div class="content">
                        <div class="title">Message</div>
                        <p>{{ message }}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if form.non_field_errors %}
        {% for m in form.non_field_errors %}
            <div class="toast error" data-time="5">
                <i class="bi bi-shield-fill-exclamation"></i>
                <div class="content">
                    <div class="title">Error</div>
                    <p>{{ m }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% if form.password.errors %}
        {% for m in form.password.errors %}
            <div class="toast error" data-time="5">
                <i class="bi bi-shield-fill-exclamation"></i>
                <div class="content">
                    <div class="title">Error</div>
                    <p>{{ m }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% if form.email.errors %}
        {% for m in form.email.errors %}
            <div class="toast error" data-time="5">
                <i class="bi bi-shield-fill-exclamation"></i>
                <div class="content">
                    <div class="title">Error</div>
                    <p>{{ m }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>


<style>
    .Options .active {
        color: var(--color-Purple);
    }

    .Options .List .active {
        color: var(--color-Purple);
    }
</style>

<nav>
    <div class="Options_Site_Name">
        <div class="Options">
            <div class="Login_And_Register">
                {% if request.user.is_authenticated %}
                    <div class="profile-dropdown">
                        <div onclick="toggle()" class="profile-dropdown-btn">
                            <div class="profile-img">
                                {% if request.user.image %}
                                    <img src="{{ request.user.image.url }}" alt="">
                                {% else %}
                                    <img src="{% static 'images/image_profile.webp' %}" alt="">
                                {% endif %}
                            </div>
                            <span>{{ request.user.name }}</span>
                        </div>
                        <ul class="profile-dropdown-list">
                            <li class="profile-dropdown-list-item">
                                <a href="{% url 'Account:UserPanel' request.user.id %}">
                                    حساب کاربری
                                </a>
                            </li>
                            <hr/>
                            <li class="profile-dropdown-list-item">
                                <a class="logout" href="{% url 'Account:LogoUt' %}">
                                    خروج از حساب
                                </a>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <a class="account" href="{% url 'Account:Login' %}">ورود</a>
                    <a class="account" href="{% url 'Account:Register' %}">ثبت نام</a>
                {% endif %}
            </div>
            <li><a href="{% url 'Home:Home' %}"
                   class="{% if request.resolver_match.url_name == 'Home' %}active{% endif %}">صفحه اصلی</a></li>
            <li class="Open_List"><i class="bi bi-caret-down-fill"></i>بافت مو</li>
            <ul class="List">
                <a
                        href="{% url 'Model:FrenchModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'FrenchModelListView' %}active{% endif %}">بافت
                        فرانسوی
                    </li>
                </a>
                <a
                        href="{% url 'Model:DutchModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'DutchModelListView' %}active{% endif %}">بافت
                        هلندی
                    </li>
                </a>
                <a
                        href="{% url 'Model:FishTailModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'FishTailModelListView' %}active{% endif %}">
                        بافت تیغ ماهی
                    </li>
                </a>
                <a
                        href="{% url 'Model:MexicanModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'MexicanModelListView' %}active{% endif %}">بافت
                        مکزیکی
                    </li>
                </a>
                <a
                        href="{% url 'Model:ChignonModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'ChignonModelListView' %}active{% endif %}">
                        شینیون بافت
                    </li>
                </a>
                <a
                        href="{% url 'Model:JournalModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'JournalModelListView' %}active{% endif %}">بافت
                        ژورنالی
                    </li>
                </a>
                <a
                        href="{% url 'Model:SpiralModelListView' %}">
                    <li class="{% if request.resolver_match.url_name == 'SpiralModelListView' %}active{% endif %}">بافت
                        اسپیرال
                    </li>
                </a>
            </ul>
            <li><a class="{% if request.resolver_match.url_name == 'AboutView' %}active{% endif %}"
                   href="{% url 'Model:AboutView' %}">بیوگرافی</a>
            </li>
        </div>
        <label class="bi-listt hamburger">
            <input type="checkbox" id="list-icon">
            <svg viewBox="0 0 32 32">
                <path class="line line-top-bottom"
                      d="M27 10 13 10C10.8 10 9 8.2 9 6 9 3.5 10.8 2 13 2 15.2 2 17 3.8 17 6L17 26C17 28.2 18.8 30 21 30 23.2 30 25 28.2 25 26 25 23.8 23.2 22 21 22L7 22"></path>
                <path class="line" d="M7 16 27 16"></path>
            </svg>
        </label>

        <div class="Site_Name">
            <a class="brand_name" href="{% url 'Home:Home' %}">Baftemo Shahrzad</a>
        </div>
    </div>
</nav>


{% block content %} {% endblock %}


<footer>
    <div class="footerContainer">
        <div class="socialIcons">
            <a href="https://wa.me/{{ whatsapp }}"><i class="bi bi-whatsapp"></i></a>
            <a href="https://www.instagram.com/{{ instagram }}"><i class="bi bi-instagram"></i></a>
            <a href="https://t.me/{{ telegram }}"><i class="bi bi-telegram"></i></a>
        </div>
        <div class="footerNav">
            <ul>
                <li><a href="{% url 'Home:Home' %}">Home</a></li>
                <li><a href="{% url 'Model:AboutView' %}">Biography</a></li>
            </ul>
        </div>

    </div>
    <div class="Date_Manufacturer">
        <p>2583 Empire; Designed by <span class="designer">Reys Official</span></p>
    </div>
</footer>

<script src="{% static 'js/user_panel.js' %}"></script>
<script src="{% static 'js/home.js' %}"></script>
<script>
    function hideToast() {
        const toastElements = document.querySelectorAll('.toast');

        toastElements.forEach((toast) => {
            toast.addEventListener('animationend', (event) => {
                if (event.animationName === 'timeOut') {
                    toast.classList.add('slideOut');
                }
                if (event.animationName === 'slideOut') {
                    toast.remove();
                }
            });
        });
    }

    let buttons = document.querySelectorAll("button");
    buttons.forEach(button => button.remove());

    let notifications = document.querySelector(".notifications_NOT_WQwqzadb");

    function createToast(toast) {
        let newToast = document.createElement("div");
        newToast.classList.add("toast", toast.type);
        newToast.setAttribute("data-time", toast.time);
        newToast.innerHTML = `
            <i class="${toast.icon}"></i>
            <div class="content">
                <div class="title">${toast.title}</div>
                <span>${toast.text}</span>
            </div>`;
        notifications.appendChild(newToast);
        setTimeout(() => {
            newToast.classList.add("slideOut");
            setTimeout(() => newToast.remove(), 300);
        }, toast.time * 1000);
    }

    hideToast();


    const inputForm = document.querySelector('.inputForm');
    const input = document.querySelector('.input');

    function detectLanguage(inputValue) {
        const persianRegex = /[\u0600-\u06FF]/;
        return persianRegex.test(inputValue) ? 'rtl' : 'ltr';
    }

    function changeDirection() {
        const inputValue = input.value;
        const direction = detectLanguage(inputValue);
        inputForm.style.direction = direction;
    }

    input.addEventListener('input', changeDirection);

    const loginButton = document.querySelector('.button-submit');
    const loaderDiv = document.querySelector('.LOD_DIV');
    const inputForms = document.querySelectorAll('.inputForm');
    const inputs = document.querySelectorAll('.input');

    loginButton.disabled = true;

    inputs.forEach((input) => {
        input.addEventListener('input', checkInputs);
    });
    loginButton.addEventListener('click', () => {
        loginButton.style.display = 'none';
        loaderDiv.style.display = 'flex';
    });

    function checkInputs() {
        let allFilled = true;
        inputs.forEach((input) => {
            if (input.value.trim() === '') {
                allFilled = false;
            }
        });
        if (allFilled) {
            loginButton.disabled = false;
        } else {
            loginButton.disabled = true;
        }
    }

    var isMenuOpen = false;

    document.getElementById("list-icon").addEventListener("click", function () {
        var optionsSiteName = document.querySelector("nav .Options_Site_Name");
        var options = document.querySelector("nav .Options_Site_Name .Options");

        if (isMenuOpen) {
            optionsSiteName.style.height = "70px";
            options.style.display = "none";
            isMenuOpen = false;
        } else {
            optionsSiteName.style.height = "400px";
            optionsSiteName.style.transition = "height .5s";
            options.style.display = "block";
            isMenuOpen = true;
        }
    });

</script>

</body>
</html>

  
  